### PR TITLE
Override target repository

### PR DESCRIPTION
**Pull request by hunomina**

### CODE REVIEW

**Comment by dev-drprasad** [comment]
Hi, thanks for the PR. This is actual useful feature.

I would like to keep configure in sync with [delete-older-releases](https://github.com/dev-drprasad/delete-older-releases). Instead of `owner`, `repo` properties, can you make change to accept `repo` in the form of `<owner>/<repo>` ? Just like `GITHUB_REPOSITORY` format. Everything else looks good

**Comment by hunomina** [comment]
Done 😉

**Comment by dev-drprasad** [comment]
Thanks for the PR!

**Comment by hunomina** [comment]
No problem 😉 Thank you for merging it 😄

**Pull request merged**
